require("dotenv").config();

module.exports = {
    development: {
        dev: process.env.NODE_ENV,
        port: process.env.DEV_PORT || 3000,
        cors: process.env.DEV_CORS,
        global_url: process.env.DEV_GLOBAL_URL,
        url: process.env.DEV_URL,
        dbUser: process.env.DEV_DB_USER,
        dbPassword: process.env.DEV_DB_PASSWORD,
        dbHost: process.env.DEV_DB_HOST,
        dbPort: process.env.DEV_DB_PORT,
        dbName: process.env.DEV_DB_NAME,
        jwt: process.env.DEV_AUTH_JWT_SECRET || "secret",
        jwt_time: process.env.DEV_JWT_TIME,
        jwt_time_refresh: process.env.DEV_JWT_TIME_REFRESH,
        verify_time: process.env.DEV_VERIFY_TIME,
        mogodbUser: process.env.DEV_MOGODB_USER,
        mogodbPassword: process.env.DEV_MOGODB_PASSWORD,
        mogodbHost: process.env.DEV_MOGODB_HOST,
        mogodbName: process.env.DEV_MOGODB_NAME,
        wsSecret: process.env.DEV_AWS_SECRET_KEY,
        wsAccess: process.env.DEV_AWS_ACCESS_KEY,
        wsNameBucket: process.env.DEV_AWS_BUCKET_NAME,
        wsRegion: process.env.DEV_AWS_REGION,
        nodemailer_mail: process.env.DEV_NODE_MAILER_MAIL,
        nodemailer_password: process.env.DEV_NODE_MAILER_PASSWORD,
        nodemailer_copy: process.env.DEV_NODE_MAILER_COPY,
        stripe: process.env.DEV_STRIPE,
        HOOK_SLACK: process.env.DEV_HOOK_SLACK,
        secret: process.env.DEV_SECRET,
    },
    production: {
        dev: process.env.NODE_ENV,
        port: process.env.PORT,
        cors: process.env.CORS,
        global_url: process.env.GLOBAL_URL,
        url: process.env.URL,
        dbUser: process.env.DB_USER,
        dbPassword: process.env.DB_PASSWORD,
        dbHost: process.env.DB_HOST,
        dbPort: process.env.DB_PORT,
        dbName: process.env.DB_NAME,
        jwt: process.env.AUTH_JWT_SECRET,
        jwt_time: process.env.JWT_TIME,
        jwt_time_refresh: process.env.JWT_TIME_REFRESH,
        verify_time: process.env.VERIFY_TIME,
        mogodbUser: process.env.MOGODB_USER,
        mogodbPassword: process.env.MOGODB_PASSWORD,
        mogodbHost: process.env.MOGODB_HOST,
        mogodbName: process.env.MOGODB_NAME,
        wsSecret: process.env.AWS_SECRET_KEY,
        wsAccess: process.env.AWS_ACCESS_KEY,
        wsNameBucket: process.env.AWS_BUCKET_NAME,
        wsRegion: process.env.AWS_REGION,
        nodemailer_mail: process.env.NODE_MAILER_MAIL,
        nodemailer_password: process.env.NODE_MAILER_PASSWORD,
        nodemailer_copy: process.env.NODE_MAILER_COPY,
        stripe: process.env.STRIPE,
        HOOK_SLACK: process.env.HOOK_SLACK,
        secret: process.env.SECRET,
    },
};
